##! This script is auto-loaded by Zeek when loading the directory.
##!
##! Best practice is to load all other .zeek files in here, in the right order if needed.

# Generated by binpac_quickstart

@load-sigs ./dpd.sig
@load ./main
