# Signature for Multicast DNS (mDNS) messages
# Generated by binpac_quickstart

signature dpd_mdns {
	
	dst_ip == 224.0.0.251,[ff02::fb]
	src-port == 5353
	dst_port == 5353
	ip-proto == udp

	# ## TODO: Define the payload. When Bro sees this regex, on
	# ## any port, it will enable your analyzer on that
	# ## connection.
	# ## payload /^MDNS/

	enable "mdns"

}
