// Generated by binpac_quickstart

#pragma once

#include "events.bif.h"


#include "analyzer/protocol/udp/UDP.h"

#include "mdns_pac.h"

namespace analyzer { namespace IoT_mDNS {

class mDNS_Analyzer: public ::zeek::analyzer::Analyzer
{
public:
	mDNS_Analyzer(zeek::Connection* conn);
	virtual ~mDNS_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();
	
	virtual void DeliverPacket(int len, const u_char* data, bool orig,
					uint64_t seq, const IP_Hdr* ip, int caplen);
	

	static ::zeek::analyzer::Analyzer* InstantiateAnalyzer(zeek::Connection* conn)
		{ return new mDNS_Analyzer(conn); }

protected:
	binpac::mDNS::mDNS_Conn* interp;
	};

} } // namespace analyzer::*
