// Generated by binpac_quickstart

#include "mDNS.h"

#include "Reporter.h"

#include "events.bif.h"

using namespace analyzer::IoT_mDNS;

mDNS_Analyzer::mDNS_Analyzer(zeek::Connection* c)

: analyzer::Analyzer("mDNS", c)

	{
	interp = new binpac::mDNS::mDNS_Conn(this);
	
	}

mDNS_Analyzer::~mDNS_Analyzer()
	{
	delete interp;
	}

void mDNS_Analyzer::Done()
	{
	
	Analyzer::Done();
	
	}

void mDNS_Analyzer::DeliverPacket(int len, const u_char* data,
	 			  bool orig, uint64_t seq, const IP_Hdr* ip, int caplen)
	{
	Analyzer::DeliverPacket(len, data, orig, seq, ip, caplen);

	try
		{
		interp->NewData(orig, data, data + len);
		}
	catch ( const binpac::Exception& e )
		{
		ProtocolViolation(fmt("Binpac exception: %s", e.c_msg()));
		}
	}

